<?

AnemicClassCreator::create(
    'Employee',
    [
        new AutoGeneratedField(
            'id', '$validators->getIntegerValidator()'),
        new AutoGeneratedField(
            'name', '$validators->getStringValidator()'),
        new AutoGeneratedField(
            'currentlyWorking', '$validators->getBooleanValidator()')
    ]);

// 매직 세터와 게터가 있습니다.
// getId() , setId(), getName()
// 유효성 검사가 명시적이지 않습니다.
// 클래스는 클래스 오토로더(class autolader)를 사용해 로드됩니다.

$john = new Employee;
$john->setId(1);
$john->setName('John');
$john->setCurrentlyWorking(true);

$john->getName(); 
// 'John' 반환
